Cypress with autogenerated client
qase-tms/qase-javascript pull request #170
Opened 2022-04-11 13:46 UTC by nl-kaidzen

- Switching to an automatically generated client;
- Support for sending custom headers;
- Updated delay timing

2022-04-12 08:48 UTC, kmalinin commented on qase-cypress/src/index.ts
> +        // eslint-disable-next-line max-len
no need to disable eslint here

2022-04-12 08:49 UTC, kmalinin commented on qase-cypress/src/index.ts
>                      this.log(
30 or 60 seconds?

2022-04-12 09:51 UTC, kamilsk approved these changes

2022-04-12 09:51 UTC, kamilsk commented on qase-cypress/src/index.ts
> +        this.options.environmentId;
please take a look: Forbidden non-null assertion

2022-04-13 12:27 UTC, nl-kaidzen commented on qase-cypress/src/index.ts
> +        // eslint-disable-next-line max-len
Fixed

2022-04-13 12:27 UTC, nl-kaidzen commented on qase-cypress/src/index.ts
>                      this.log(
Fixed 30 sec

2022-04-13 12:30 UTC, kamilsk requested changes

2022-04-13 12:30 UTC, kamilsk commented on qase-cypress/src/index.ts
> +                const endTime = Date.now() + 30e3;
Please make it configurable

2022-04-13 19:38 UTC, kamilsk approved these changes

2022-04-13 19:38 UTC, kamilsk commented on qase-cypress/src/index.ts
> +                        chalk`{red Could not send all results for ${delay} seconds after run. Please contact Qase Team.}`
did you see <img width="473" alt="image" src="https://user-images.githubusercontent.com/1165416/163257153-7267013a-a446-4211-9543-8e3074ca60c8.png">

2022-04-13 19:39 UTC, merged