Use autogenerated client in playwright reporter
qase-tms/qase-javascript pull request #182
Opened 2022-04-14 20:11 UTC by kmalinin

2022-04-15 05:44 UTC, kamilsk requested changes
please try to fix sonarcloud notice

2022-04-15 10:18 UTC, sklmx commented
> please try to fix sonarcloud notice

fixed

2022-04-15 19:22 UTC, kamilsk approved these changes

2022-04-18 07:05 UTC, nl-kaidzen approved these changes

2022-04-18 13:25 UTC, kamilsk requested changes
merge conflicts

2022-04-19 07:53 UTC, kamilsk approved these changes

2022-04-19 07:53 UTC, merged