Testcafe reporter with autogenerated client
qase-tms/qase-javascript pull request #183
Opened 2022-04-15 10:53 UTC by kmalinin

2022-04-15 11:53 UTC, nl-kaidzen commented on qase-testcafe/examples/.qaserc
> +    "environmentId": 1,
Let's change back "api_key" and "project_code". We used these "keywords" at Readme.md

2022-04-15 11:53 UTC, nl-kaidzen commented on qase-testcafe/examples/package.json
> +  "version": "1.0.1",
-alpha.0

2022-04-15 11:59 UTC, nl-kaidzen commented on qase-testcafe/package.json
> +  "version": "v1.2.0-alpha.4",
Why minor and alpha.4?

2022-04-15 12:01 UTC, nl-kaidzen reviewed
Resolve issues from GithubActions with unused variables:
- endtime
-passed,
etc...

2022-04-15 19:21 UTC, kamilsk approved these changes

2022-04-15 19:21 UTC, kamilsk commented on qase-testcafe/examples/.qaserc
> +    "projectCode": "project_code"
why did you drop comma?

2022-04-18 06:53 UTC, nl-kaidzen approved these changes

2022-04-18 13:25 UTC, kamilsk requested changes
so slow communication

2022-04-19 12:58 UTC, kamilsk approved these changes

2022-04-19 12:58 UTC, merged